services:
  - type: web
    name: feedback-backend
    env: python
    plan: free
    rootDir: feedback-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: web
    name: feedback-frontend
    env: node
    plan: free
    rootDir: feedback-frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    staticPublishPath: build
