from flask import Flask, request, jsonify
from flask_cors import CORS
from pymongo import MongoClient
from datetime import datetime
from bson import ObjectId

app = Flask(__name__)
CORS(app)

# MongoDB connection
client = MongoClient("mongodb+srv://Sahana:dbsahana2003@cluster0.ecwyvd5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client["feedback_db"]
collection = db["feedbacks"]

# POST /feedback - Add new feedback
@app.route('/feedback', methods=['POST'])
def add_feedback():
    data = request.json
    feedback = {
        "name": data.get("name"),
        "email": data.get("email"),
        "message": data.get("message"),
        "timestamp": datetime.utcnow()
    }
    collection.insert_one(feedback)
    return jsonify({"message": "Feedback submitted successfully"}), 201

# GET /feedback - Get all feedbacks
@app.route('/', methods=['GET'])
def get_feedback():
    feedbacks = []
    for fb in collection.find():
        feedbacks.append({
            "_id": str(fb.get("_id")),  # Auto-generated by MongoDB
            "name": fb.get("name"),
            "email": fb.get("email"),
            "message": fb.get("message"),
            "timestamp": fb.get("timestamp").isoformat() if fb.get("timestamp") else ""
        })
    return jsonify(feedbacks)

# DELETE /feedback/<id> - Delete a feedback by ID
@app.route('/feedback/<id>', methods=['DELETE'])
def delete_feedback(id):
    result = collection.delete_one({"_id": ObjectId(id)})
    if result.deleted_count == 1:
        return jsonify({"message": "Feedback deleted successfully"}), 200
    else:
        return jsonify({"error": "Feedback not found"}), 404

if __name__ == '__main__':
    app.run(debug=True)
